/**
 * /api/library — reusable building blocks (Style / Brand / Universe / Character).
 *
 * One endpoint over the four asset tables. Each item is generated by its engine
 * (so creation is AI-assisted + contract-validated) and persisted as JSONB.
 *
 * GET    /api/library?workspace_id=&type=style|brand|universe|character   → { items }
 * POST   /api/library  { workspace_id, type, ...engineInput }
 *          → runs the matching engine, saves, returns { item }
 * DELETE /api/library?type=&id=<id>                                       → { deleted }
 *
 * type → { table, column, engine }
 */
import { getServerSupabase, coerceWorkspaceId } from './_db.js'
import { runEngine } from './_engines/run.js'

const TYPES = {
  style:     { table: 'style_profiles', column: 'profile',   engine: 'style' },
  brand:     { table: 'brands',         column: 'brand',     engine: 'brand' },
  universe:  { table: 'universes',      column: 'universe',  engine: 'universe' },
  character: { table: 'characters',     column: 'character', engine: 'character' }
}

export default async function handler(req, res) {
  const db = getServerSupabase()
  const type = (req.method === 'DELETE' ? req.query.type : (req.method === 'GET' ? req.query.type : req.body?.type))
  const cfg = TYPES[type]
  if (!cfg) return res.status(400).json({ error: `type must be one of: ${Object.keys(TYPES).join(', ')}` })

  if (req.method === 'GET') {
    const { workspace_id } = req.query
    if (!db) return res.status(200).json({ items: [], mode: 'no-db' })
    const wsId = coerceWorkspaceId(workspace_id)
    const { data, error } = await db.from(cfg.table)
      .select(`id, name, ${cfg.column}, created_at`)
      .eq('workspace_id', wsId).order('created_at', { ascending: false }).limit(100)
    if (error) return res.status(500).json({ error: error.message })
    const items = (data || []).map((r) => ({ id: r.id, name: r.name, created_at: r.created_at, data: r[cfg.column] }))
    return res.status(200).json({ items })
  }

  if (req.method === 'POST') {
    const { workspace_id, type: _t, ...engineInput } = req.body || {}
    if (!engineInput.name) return res.status(400).json({ error: 'name required' })
    if (!db) return res.status(503).json({ error: 'Supabase not configured' })
    const wsId = coerceWorkspaceId(workspace_id)

    // Generate the building block via its engine (AI-assisted + contract-validated).
    const ran = await runEngine(cfg.engine, { ...engineInput, workspace_id }, { workspaceId: wsId, db })
    const contractObj = ran.output

    const row = { workspace_id: wsId, name: engineInput.name, [cfg.column]: contractObj }
    // characters can belong to a universe
    if (type === 'character' && engineInput.universe_id) row.universe_id = engineInput.universe_id

    const { data, error } = await db.from(cfg.table).insert(row).select().single()
    if (error) return res.status(500).json({ error: error.message })
    return res.status(200).json({ item: { id: data.id, name: data.name, data: data[cfg.column] } })
  }

  if (req.method === 'DELETE') {
    const { id } = req.query
    if (!id) return res.status(400).json({ error: 'id required' })
    if (!db) return res.status(503).json({ error: 'Supabase not configured' })
    const { error } = await db.from(cfg.table).delete().eq('id', id)
    if (error) return res.status(500).json({ error: error.message })
    return res.status(200).json({ deleted: true })
  }

  return res.status(405).json({ error: 'Method not allowed' })
}